### ISSUE TITLE
|| Promise fallback won't work if global is not defined

### ISSUE THREAD

**Issue by dantman** [tunnckoCore/native-promise#2]
The `|| Promise` fallback in this line might not do anything.

``` js
module.exports = global.Promise || Promise
```

If `global` is not defined then `Promise` won't be used, instead the package will return false without trying to use `Promise`.

**Comment by tunnckoCore** [comment]
Hm. Don't know, wasn't sure enough. In anyway it will return `false` from the `catch` if something is wrong. What's the problem, I don't get it?

**Comment by dantman** [comment]
In the case where `Promise` exists but `global` does not, the line will error and `native-promise` will return `false` instead of the native promise.

**Comment by tunnckoCore** [comment]
Oh, yea. So need to switch them?

Wanna PR?

**Comment by dantman** [comment]
Ok, #3 should work. I could have done it with a nested set of `try {} catch`es as well, but `typeof` was sufficient to catch all the possible sources of `Promise`.

**Comment by tunnckoCore** [comment]
I'm going to publish it.
